# docker-compose for development
version: "3"

services:
  server:
    image: node:10.15-alpine
    ports:
      - 3000:3000
      - 9229:9229
    user: $UID:0
    working_dir: /repo
    command: echo "Use yarn start or whatever"
    env_file:
      - src/environments/.env
    volumes:
      - ./:/repo