# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &default_docker_image circleci/node:10.15

var_2: &cache_key v1-dependencies-{{ checksum "yarn.lock" }}

version: 2.1

executors:
  my-executor:
    docker:
      - image: *default_docker_image
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: my-executor
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - *cache_key
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: *cache_key
      - persist_to_workspace:
          root: .
          paths: .

  linter:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  test_cov:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test:cov

  build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build

workflows:
  version: 2
  tests:
    jobs:
      - checkout_code
      - linter:
          requires:
            - checkout_code
      - test_cov:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
